=== Dethorhyne/PhpAppCollection/xmlLoot/Assets/XML/DBSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Database">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Towns">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Town" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:integer" name="PosX" use="optional"/>
                      <xs:attribute type="xs:integer" name="PosY" use="optional"/>
                      <xs:attribute type="xs:string" name="Active" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Locations">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Location" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ItemFamilies">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="ItemFamily" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ItemPlacements">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="ItemPlacement" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ItemTypes">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="ItemType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Buildings">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Building" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element name="Locations">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Location" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:byte" name="ItemSpawns"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="TownBuildings">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="TownBuilding" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="Town" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Items">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Item" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="ItemFamily"/>
                    <xs:element type="xs:string" name="ItemPlacement"/>
                    <xs:element type="xs:string" name="ItemType"/>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element name="Locations">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Location" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:integer" name="Rarity"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Dethorhyne/PhpAppCollection/xmlLoot/Assets/XML/XMLDB.xml
<?xml version="1.0" encoding="utf-8"?>

<Database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DBSchema.xsd">
  <Towns>
    <Town PosX="45" PosY="129" Active="True">Balota</Town>
    <Town PosX="151" PosY="15" Active="True">Berezhki</Town>
    <Town PosX="129" PosY="53" Active="True">Berezino</Town>
    <Town PosX="33" PosY="114" Active="True">Bor</Town>
    <Town PosX="56" PosY="128" Active="True">Chapaevsk</Town>
    <Town PosX="121" PosY="16" Active="True">Chernaya Polana</Town>
    <Town PosX="67" PosY="127" Active="True">Chernogorsk</Town>
    <Town PosX="114" PosY="86" Active="True">Dolina</Town>
    <Town PosX="33" PosY="104" Active="True">Drozhino</Town>
    <Town PosX="66" PosY="117" Active="True">Dubky</Town>
    <Town PosX="104" PosY="55" Active="True">Dubrovka</Town>
    <Town PosX="103" PosY="132" Active="True">Elektrozavodsk</Town>
    <Town PosX="96" PosY="64" Active="True">Gorka</Town>
    <Town PosX="59" PosY="50" Active="True">Grishino</Town>
    <Town PosX="84" PosY="86" Active="True">Guglovo</Town>
    <Town PosX="85" PosY="34" Active="True">Gvozdno</Town>
    <Town PosX="53" PosY="67" Active="True">Kabanino</Town>
    <Town PosX="19" PosY="131" Active="True">Kamenka</Town>
    <Town PosX="66" PosY="7" Active="True">Kamensk</Town>
    <Town PosX="121" PosY="118" Active="True">Kamyshovo</Town>
    <Town PosX="127" PosY="6" Active="True">Karmanovka</Town>
    <Town PosX="123" PosY="43" Active="True">Khelm</Town>
    <Town PosX="36" PosY="128" Active="True">Komarovo</Town>
    <Town PosX="44" PosY="107" Active="True">Kozlovka</Town>
    <Town PosX="64" PosY="2" Active="True">Krasnoe</Town>
    <Town PosX="111" PosY="30" Active="True">Krasnostav</Town>
    <Town PosX="27" PosY="53" Active="True">Lopatino</Town>
    <Town PosX="75" PosY="102" Active="True">Mogilevka</Town>
    <Town PosX="112" PosY="98" Active="True">Msta</Town>
    <Town PosX="20" PosY="79" Active="True">Myshkino</Town>
    <Town PosX="11" PosY="81" Active="True">Myshkino Military Base</Town>
    <Town PosX="58" PosY="106" Active="True">Nadezhdino</Town>
    <Town PosX="92" PosY="7" Active="True">Nagornoe</Town>
    <Town PosX="129" PosY="74" Active="True">Nizhnoye</Town>
    <Town PosX="36" PosY="22" Active="True">Novaya Petrovka</Town>
    <Town PosX="116" PosY="9" Active="True">Novodmitrovsk</Town>
    <Town PosX="61" PosY="121" Active="True">Novoselky</Town>
    <Town PosX="70" PosY="76" Active="True">Novy Sobor</Town>
    <Town PosX="133" PosY="24" Active="True">Olsha</Town>
    <Town PosX="121" PosY="80" Active="True">Orlovets</Town>
    <Town PosX="16" PosY="115" Active="True">Pavlovo</Town>
    <Town PosX="45" PosY="88" Active="True">Pogorevka</Town>
    <Town PosX="107" PosY="71" Active="True">Polana</Town>
    <Town PosX="59" PosY="17" Active="True">Polesovo</Town>
    <Town PosX="79" PosY="119" Active="True">Prigorodki</Town>
    <Town PosX="49" PosY="97" Active="True">Pulkovo</Town>
    <Town PosX="91" PosY="115" Active="True">Pusta</Town>
    <Town PosX="30" PosY="74" Active="True">Pustoshka</Town>
    <Town PosX="63" PosY="25" Active="True">Ratnoe</Town>
    <Town PosX="47" PosY="84" Active="True">Rogovo</Town>
    <Town PosX="80" PosY="25" Active="True">Severograd</Town>
    <Town PosX="96" PosY="86" Active="True">Shakhovka</Town>
    <Town PosX="14" PosY="32" Active="True">Sinistok</Town>
    <Town PosX="115" PosY="2" Active="True">Smirnovo</Town>
    <Town PosX="134" PosY="92" Active="True">Solnichniy</Town>
    <Town PosX="25" PosY="90" Active="True">Sosnovka</Town>
    <Town PosX="101" PosY="97" Active="True">Staroye</Town>
    <Town PosX="61" PosY="76" Active="True">Stary Sobor</Town>
    <Town PosX="49" PosY="2" Active="True">Stary Yar</Town>
    <Town PosX="95" PosY="15" Active="True">Svergino</Town>
    <Town PosX="139" PosY="21" Active="True">Svetlojarsk</Town>
    <Town PosX="34" PosY="5" Active="True">Tisy</Town>
    <Town PosX="28" PosY="29" Active="True">Topolniki</Town>
    <Town PosX="128" PosY="109" Active="True">Tulga</Town>
    <Town PosX="136" PosY="12" Active="True">Turovo</Town>
    <Town PosX="22" PosY="42" Active="True">Vavilovo</Town>
    <Town PosX="38" PosY="64" Active="True">Vybor</Town>
    <Town PosX="45" PosY="69" Active="True">Veresnik Military Complex</Town>
    <Town PosX="65" PosY="91" Active="True">Vyshnoye</Town>
    <Town PosX="45" PosY="21" Active="True">Zaprudnoe</Town>
    <Town PosX="27" PosY="99" Active="True">Zelenogorsk</Town>
    <Town PosX="102" PosY="33" Active="True">Black Mountain Castle</Town>
    <Town PosX="69" PosY="40" Active="True">Devils Castle</Town>
    <Town PosX="74" PosY="62" Active="True">Old Fields Castle</Town>
    <Town PosX="112" PosY="110" Active="True">Rog Castle</Town>
    <Town PosX="135" PosY="123" Active="True">Skalisty Island</Town>
    <Town PosX="65" PosY="97" Active="True">Zub Castle</Town>
    <Town PosX="26" PosY="140" Active="True">Prison Island</Town>
    <Town PosX="21" PosY="120" Active="True">Pavlovo Military Base</Town>
    <Town PosX="37" PosY="93" Active="True">Green Mountain Military Base</Town>
    <Town PosX="45" PosY="50" Active="True">North West Airfield</Town>
    <Town PosX="121" PosY="26" Active="True">North East Airfield</Town>
    <Town PosX="13" PosY="11" Active="True">Tisy Military Base</Town>
    <Town PosX="81" PosY="43" Active="True">Holiday Camp Gordy</Town>
    <Town PosX="103" PosY="118" Active="True">Holiday Camp Kometa</Town>
    <Town PosX="72" PosY="83" Active="True">Holiday Camp Nadezhda</Town>
    <Town PosX="149" PosY="9" Active="True">Student Summer Camp</Town>
    <Town PosX="85" PosY="14" Active="True">Summer Camp Arsenievo</Town>
    <Town PosX="70" PosY="110" Active="True">Summer Camp Strojtel</Town>
    <Town PosX="115" PosY="47" Active="True">Summer Camp Druzhba</Town>
  </Towns>
  <Locations>
    <Location>Camping</Location>
    <Location>Civilian</Location>
    <Location>Farm</Location>
    <Location>Fire Stations</Location>
    <Location>Fishing</Location>
    <Location>Forester</Location>
    <Location>Historical</Location>
    <Location>Hunting</Location>
    <Location>Hygiene</Location>
    <Location>Kitchen</Location>
    <Location>Medical</Location>
    <Location>Military East</Location>
    <Location>Military West</Location>
    <Location>Office</Location>
    <Location>Police</Location>
    <Location>Prison</Location>
    <Location>School</Location>
    <Location>Work</Location>
  </Locations>
  <ItemFamilies>
    <ItemFamily>Clothing</ItemFamily>
    <ItemFamily>Equipment</ItemFamily>
    <ItemFamily>Food</ItemFamily>
    <ItemFamily>Drink</ItemFamily>
    <ItemFamily>Resources</ItemFamily>
    <ItemFamily>Medical Supply</ItemFamily>
    <ItemFamily>Weapon</ItemFamily>
  </ItemFamilies>
  <ItemPlacements>
    <ItemPlacement>Head</ItemPlacement>
    <ItemPlacement>Upper body</ItemPlacement>
    <ItemPlacement>Lower body</ItemPlacement>
    <ItemPlacement>Back</ItemPlacement>
    <ItemPlacement>Hand</ItemPlacement>
    <ItemPlacement>Melee</ItemPlacement>
    <ItemPlacement>Ranged</ItemPlacement>
  </ItemPlacements>
  <ItemTypes>
    <ItemType>Eyewear</ItemType>
    <ItemType>Hat</ItemType>
    <ItemType>Helmet</ItemType>
    <ItemType>Mask</ItemType>
    <ItemType>Shirt</ItemType>
    <ItemType>Jacket</ItemType>
    <ItemType>Holster</ItemType>
    <ItemType>Hands &amp; Arms</ItemType>
    <ItemType>Vest</ItemType>
    <ItemType>Pants</ItemType>
    <ItemType>Shoes</ItemType>
    <ItemType>Backpack</ItemType>
    <ItemType>Tent</ItemType>
    <ItemType>Container</ItemType>
    <ItemType>Cooking</ItemType>
    <ItemType>Devices</ItemType>
    <ItemType>Light Sources</ItemType>
    <ItemType>Tools</ItemType>
    <ItemType>Other</ItemType>
    <ItemType>Canned Goods</ItemType>
    <ItemType>Dry Food</ItemType>
    <ItemType>Bottle</ItemType>
    <ItemType>Can</ItemType>
    <ItemType>Seeds</ItemType>
    <ItemType>Manmade</ItemType>
    <ItemType>Bat</ItemType>
    <ItemType>Blunt</ItemType>
    <ItemType>Light Blunt</ItemType>
    <ItemType>Heavy Blunt</ItemType>
    <ItemType>Slash</ItemType>
    <ItemType>Chop</ItemType>
    <ItemType>Heavy Slash</ItemType>
    <ItemType>Heavy Chop</ItemType>
    <ItemType>Stab</ItemType>
    <ItemType>Chainsaw</ItemType>
    <ItemType>Prod</ItemType>
    <ItemType>Bow</ItemType>
    <ItemType>Pistol</ItemType>
    <ItemType>Rifle</ItemType>
    <ItemType>Assault Rifle</ItemType>
    <ItemType>Marksman Rifle</ItemType>
    <ItemType>Sniper Rifle</ItemType>
    <ItemType>Submachine Gun</ItemType>
    <ItemType>Shotgun</ItemType>
    <ItemType>Explosive</ItemType>
  </ItemTypes>
  <Buildings>
    <Building>
      <Name>ATC Tower</Name>
      <Locations>
        <Location>Military East</Location>
        <Location>Military West</Location>
      </Locations>
      <ItemSpawns>5</ItemSpawns>
    </Building>
    <Building>
      <Name>Barn</Name>
      <Locations>
        <Location>Civilian</Location>
        <Location>Farm</Location>
        <Location>Work</Location>
      </Locations>
      <ItemSpawns>6</ItemSpawns>
    </Building>
    <Building>
      <Name>Boathouse</Name>
      <Locations>
        <Location>Civilian</Location>
      </Locations>
      <ItemSpawns>3</ItemSpawns>
    </Building>
    <Building>
      <Name>Camp House</Name>
      <Locations>
        <Location>Camping</Location>
        <Location>Civilian</Location>
        <Location>Forester</Location>
        <Location>Kitchen</Location>
      </Locations>
      <ItemSpawns>2</ItemSpawns>
    </Building>
    <Building>
      <Name>Castle</Name>
      <Locations>
        <Location>Civilian</Location>
        <Location>Historical</Location>
      </Locations>
      <ItemSpawns>6</ItemSpawns>
    </Building>
    <Building>
      <Name>Church</Name>
      <Locations>
        <Location>Civilian</Location>
      </Locations>
      <ItemSpawns>2</ItemSpawns>
    </Building>
    <Building>
      <Name>City Hall</Name>
      <Locations>
